version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: attendance-postgres
    ports:
      - "6095:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance-net

  backend:
    build:
      context: ./Backend
    container_name: attendance-backend
    ports:
      - "3050:3050"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_NAME: attendance_db
      DB_PORT: 5432
    networks:
      - attendance-net

  employee-attendance:
    build:
      context: ./Employee-Attendance
    container_name: employee-attendance
    ports:
      - "9095:80"
    depends_on:
      - backend
    networks:
      - attendance-net

  hr-attendance:
    build:
      context: ./HR-Attendance
    container_name: hr-attendance
    ports:
      - "9096:80"
    depends_on:
      - backend
    networks:
      - attendance-net

volumes:
  postgres_data:

networks:
  attendance-net:
